name       : python-psutil
version    : 5.4.8
release    : 11
source     :
    - https://github.com/giampaolo/psutil/archive/release-5.4.8.tar.gz : c10f5054e04551fcbd1703bbc2aef0f8327a32c673322aacb4c79fc84cb0826b
license    : BSD-3-Clause
component  : programming.python
summary    : A cross-platform process and system utilities module for Python
description: |
    A cross-platform process and system utilities module for Python
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
rundeps    :
    - python-enum34
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
