name       : python-psutil
version    : 5.4.2
release    : 7
source     :
    - https://github.com/giampaolo/psutil/archive/release-5.4.2.tar.gz : a5854423865170862a1bc4aea8a4fa01b8126a52ee58885214932e11bad826d5
license    : BSD-3-Clause
component  : programming.python
summary    : A cross-platform process and system utilities module for Python
description: |
    A cross-platform process and system utilities module for Python
builddeps  :
    - pkgconfig(python-3.5)
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
