name       : python-psutil
version    : 5.9.1
release    : 25
source     :
    - https://github.com/giampaolo/psutil/archive/refs/tags/release-5.9.1.tar.gz : 9717c7fae41d9b81fe2589d17206920401078aa5329a571b13299e3aef978362
homepage   : https://github.com/giampaolo/psutil
license    : BSD-3-Clause
component  : programming.python
summary    : Cross-platform lib for process and system monitoring in Python
description: |
    psutil (process and system utilities) is a cross-platform library for retrieving information on running processes and system utilization (CPU, memory, disks, network, sensors) in Python.
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
