name       : python-psutil
version    : 5.8.0
release    : 21
source     :
    - https://github.com/giampaolo/psutil/archive/release-5.8.0.tar.gz : c015248da36109ffaa15f46fce8c0003f678cfaa408090f466c80318885e7abf
homepage   : https://github.com/giampaolo/psutil
license    : BSD-3-Clause
component  : programming.python
summary    : Cross-platform lib for process and system monitoring in Python
description: |
    psutil (process and system utilities) is a cross-platform library for retrieving information on running processes and system utilization (CPU, memory, disks, network, sensors) in Python.
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
rundeps    :
    - python-enum34
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
