name       : python-psutil
version    : 5.7.2
release    : 18
source     :
    - https://github.com/giampaolo/psutil/archive/release-5.7.2.tar.gz : 05192e5082838bf264af8c7f0be9a00a3075daab890ab93e1b60a6a60ec43c2a
homepage   : https://github.com/giampaolo/psutil
license    : BSD-3-Clause
component  : programming.python
summary    : Cross-platform lib for process and system monitoring in Python
description: |
    psutil (process and system utilities) is a cross-platform library for retrieving information on running processes and system utilization (CPU, memory, disks, network, sensors) in Python.
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
rundeps    :
    - python-enum34
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
