name       : python-psutil
version    : 5.9.4
release    : 27
source     :
    - https://github.com/giampaolo/psutil/archive/refs/tags/release-5.9.4.tar.gz : 721a5c727ee476f36cd1a4d44b1f6dc29a345a62eedfb1420da4b14422748bdb
homepage   : https://github.com/giampaolo/psutil
license    : BSD-3-Clause
component  : programming.python
summary    : Cross-platform lib for process and system monitoring in Python
description: |
    psutil (process and system utilities) is a cross-platform library for retrieving information on running processes and system utilization (CPU, memory, disks, network, sensors) in Python.
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
