name        : python-psutil
version     : 4.1.0
release     : 3
source     :
    - https://github.com/giampaolo/psutil/archive/release-4.1.0.tar.gz : 5d3fb2c74ec79f2bbebaccb935d929b26c9051f055f734191a06ba6987de02b1
license     : BSD
component   : programming.python
summary     : A cross-platform process and system utilities module for Python
description : |
    A cross-platform process and system utilities module for Python
builddeps  :
    - pkgconfig(python-2.7)
    - pkgconfig(python-3.5)
build      : |
    for py in "python" "python3" ; do
        ${py} setup.py build
    done
install    : |
    for py in "python" "python3" ; do
        ${py} setup.py install --root=%installroot% --no-compile -O0
    done
