name       : python-psutil
version    : 5.6.3
release    : 14
source     :
    - https://github.com/giampaolo/psutil/archive/release-5.6.3.tar.gz : 55b86dc0a9fc4e258ae5d86d6edf317432a4e3dc45c7324b8a82838b07e74f4a
license    : BSD-3-Clause
component  : programming.python
summary    : Cross-platform lib for process and system monitoring in Python
description: |
    psutil (process and system utilities) is a cross-platform library for retrieving information on running processes and system utilization (CPU, memory, disks, network, sensors) in Python.
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
rundeps    :
    - python-enum34
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
