name       : python-psutil
version    : 5.9.5
release    : 29
source     :
    - https://github.com/giampaolo/psutil/archive/refs/tags/release-5.9.5.tar.gz : fba07e5d76e129ee1a374ea911e9bfc4161636260e33d055abb2b426ed182429
homepage   : https://github.com/giampaolo/psutil
license    : BSD-3-Clause
component  : programming.python
summary    : Cross-platform lib for process and system monitoring in Python
description: |
    psutil (process and system utilities) is a cross-platform library for retrieving information on running processes and system utilization (CPU, memory, disks, network, sensors) in Python.
builddeps  :
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install
